build: Make helper scripts more useful
...and less noisy.

diff --git a/compileall b/compileall
--- a/compileall
+++ b/compileall
@@ -20,15 +20,24 @@
 #
 # SPDX-License-Identifier: Apache-2.0
 
-# Fail on error, fail on unbound variable, verbose mode, xtrace mode, pipefail mode.
-set -euvxo pipefail
+# Fail on error, fail on unbound variable, pipefail mode.
+set -euo pipefail
 
-# Check legacy state.
-for arg in "$@"; do [ "${arg}" = '--legacy' ] && HCSCR_LEGACY=true; done
-if [ "${HCSCR_LEGACY:-}" = "true" ]; then
+# Check args.
+if [ "${1:-}" = "legacy" ]; then
     # Build with legacy.
-    ./gradlew -Dru.vidtu.hcscr.legacy=true assemble
-else
+    echo "SCRIPT: Building in legacy mode..."
+    ./gradlew -Dru.vidtu.hcscr.legacy=true assemble && true
+    echo "SCRIPT: Build in legacy mode exited with code ${?}."
+elif [ "${1:-}" = "normal" ]; then
     # Build without legacy.
-    ./gradlew assemble
+    echo "SCRIPT: Building in normal mode..."
+    ./gradlew assemble && true
+    echo "SCRIPT: Build in normal mode exited with code ${?}."
+else
+    # Fail.
+    echo 'SCRIPT: You must specify the mode of execution.'
+    echo 'Normal (Beta/Active): ./compileall normal'
+    echo 'Legacy (Beta/Active/Legacy): ./compileall legacy'
+    exit 2
 fi
diff --git a/launch b/launch
--- a/launch
+++ b/launch
@@ -20,8 +20,17 @@
 #
 # SPDX-License-Identifier: Apache-2.0
 
-# Fail on error, fail on unbound variable, verbose mode, xtrace mode, pipefail mode.
-set -euvxo pipefail
+# Fail on error, fail on unbound variable, pipefail mode.
+set -euo pipefail
+
+# Check args.
+if [ "${#}" -eq 0 ]; then
+    echo 'SCRIPT: You must specify the version to launch.'
+    echo 'Example: ./launch 1.16.5-fabric'
+    exit 1
+fi
 
 # Launch.
-./gradlew "-Dru.vidtu.hcscr.only=${1}" "${1}:runClient"
+echo "SCRIPT: Launching '${1}'..."
+./gradlew "-Dru.vidtu.hcscr.only=${1}" "${1}:runClient" && true
+echo "SCRIPT: Launch for '${1}' exited with code ${?}."
diff --git a/launchall b/launchall
--- a/launchall
+++ b/launchall
@@ -20,14 +20,23 @@
 #
 # SPDX-License-Identifier: Apache-2.0
 
-# Fail on error, fail on unbound variable, verbose mode, xtrace mode, pipefail mode.
-set -euvxo pipefail
+# Fail on error, fail on unbound variable, pipefail mode.
+set -euo pipefail
 
 # Iterate.
+echo "SCRIPT: Launching all versions..."
 for folder in versions/*; do
     # Extract the version (only the folder name) from the full relative path.
     version=$(basename -- "${folder}")
 
-    # Launch, unless ".ignored" exists.
-    [ -f "${folder}/.ignored" ] || ./gradlew "-Dru.vidtu.hcscr.only=${version}" "${version}:runClient"
+    # Skip if ".ignored" exists.
+    [ -f "${folder}/.ignored" ] && echo "SCRIPT: Skipping '${version}' because of the '.ignored' file." && continue
+
+    # Launch.
+    echo "SCRIPT: Launching '${version}'..."
+    ./gradlew "-Dru.vidtu.hcscr.only=${version}" "${version}:runClient" && true
+    exit="${?}"
+    echo "SCRIPT: Launch for '${version}' exited with code ${exit}."
+    [ "${exit}" -ne 0 ] && read -srn1 -p "SCRIPT: Non-zero exit code. Press any key to continue." exit && echo
 done
+echo "SCRIPT: Done launching all versions."
diff --git a/reset b/reset
--- a/reset
+++ b/reset
@@ -20,8 +20,10 @@
 #
 # SPDX-License-Identifier: Apache-2.0
 
-# Fail on error, fail on unbound variable, verbose mode, xtrace mode, pipefail mode.
-set -euvxo pipefail
+# Fail on error, fail on unbound variable, pipefail mode.
+set -euo pipefail
 
 # Reset.
-./gradlew "Reset active project"
+echo "SCRIPT: Resetting active project..."
+./gradlew "Reset active project" && true
+echo "SCRIPT: Resetting active project exited with code ${?}."
diff --git a/switch b/switch
--- a/switch
+++ b/switch
@@ -20,8 +20,17 @@
 #
 # SPDX-License-Identifier: Apache-2.0
 
-# Fail on error, fail on unbound variable, verbose mode, xtrace mode, pipefail mode.
-set -euvxo pipefail
+# Fail on error, fail on unbound variable, pipefail mode.
+set -euo pipefail
+
+# Check args.
+if [ "${#}" -eq 0 ]; then
+    echo 'SCRIPT: You must specify the version to switch.'
+    echo 'Example: ./switch 1.16.5-fabric'
+    exit 1
+fi
 
 # Switch.
+echo "SCRIPT: Switching to '${1}'..."
 ./gradlew "Set active project to ${1}"
+echo "SCRIPT: Switching to '${1}' exited with code ${?}."
