chore: Make helper scripts not require bash

diff --git a/launch b/launch
--- a/launch
+++ b/launch
@@ -1,4 +1,5 @@
-#!/usr/bin/env bash
+#!/bin/sh
+#
 # HCsCR is a third-party mod for Minecraft Java Edition
 # that allows removing the end crystals faster.
 #
@@ -19,5 +20,8 @@
 #
 # SPDX-License-Identifier: Apache-2.0
 
-echo "> Launching $1..."
+# Fail on error, fail on unbound variable, verbose mode, xtrace mode.
+set -euvx
+
+# Launch.
 ./gradlew "$1:runClient"
diff --git a/launchall b/launchall
--- a/launchall
+++ b/launchall
@@ -1,4 +1,5 @@
-#!/usr/bin/env bash
+#!/bin/sh
+#
 # HCsCR is a third-party mod for Minecraft Java Edition
 # that allows removing the end crystals faster.
 #
@@ -19,8 +20,11 @@
 #
 # SPDX-License-Identifier: Apache-2.0
 
+# Fail on error, fail on unbound, verbose mode, xtrace mode.
+set -euvx
+
+# Iterate.
 for folder in versions/*; do
     version=$(basename "$folder")
-    echo "> Launching $version..."
     ./gradlew "${version}:runClient"
 done
diff --git a/reset b/reset
--- a/reset
+++ b/reset
@@ -1,4 +1,5 @@
-#!/usr/bin/env bash
+#!/bin/sh
+#
 # HCsCR is a third-party mod for Minecraft Java Edition
 # that allows removing the end crystals faster.
 #
@@ -19,4 +20,8 @@
 #
 # SPDX-License-Identifier: Apache-2.0
 
+# Fail on error, fail on unbound variable, verbose mode, xtrace mode.
+set -euvx
+
+# Reset.
 ./gradlew "Reset active project"
